version: "3.9"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ikkidominico/bluewater
    container_name: bluewater-app
    tty: true
    working_dir: /var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: unless-stopped
    networks:
      - bluewater-network

  server:
    image: nginx:stable
    container_name: bluewater-server
    tty: true
    ports:
      - "8080:80"
      - "4433:443"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - bluewater-network


  database:
    image: postgres:latest
    container_name: bluewater-database
    tty: true
    environment:
      POSTGRES_DB: bluewater
      POSTGRES_USER: bluewater
      POSTGRES_PASSWORD: bluewater
      SERVICE_NAME: psql
      SERVICE_TAGS: dev
    ports: 
      - "5432:5432"
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bluewater"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - bluewater-network

networks:
  bluewater-network:
    driver: bridge

volumes:
  pgsqldata:
    driver: local